version: '3.8'
services:
  node_backend:
    container_name: moneeb_node
    image: moneebshammout/moneeb_node:1.0.0
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PGUSER=postmoneeb
      - PGPASSWORD=shammout123
      - PGDATABASE=movies
      - PGHOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postmoneeb
      - POSTGRES_PASSWORD=shammout123
      - POSTGRES_DB=movies
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
